### PR TITLE
Add Web Development Resources into the community website

### PR DESCRIPTION
**Pull request by aachal28**
I have added the education resources for web development and updated contributors information

### CODE REVIEW

**Comment by melvincwng** [comment]
Hi, @aachal28, thanks for your PR. Before I review the PR, I have 2 questions:

1. Have you joined our organization? Please join our organization first before making PR/contributions to the codebase. You can follow the [instructions here](https://github.com/Your-First-Open-Source-Project/start-here#how-to-join-this-organization) to join our organization.

2. There are a couple of links that are not clickable at the moment. Will you be constantly updating your Web Development Resources repo in the future? See screenshot for more info.
image

**Comment by melvincwng** [comment]
Also another question @aachal28, what is the License for your Web Development Resource repository?

Is it going to be MIT License? GPL-3 license? or?

Please add an appropriate open-source license (e.g. MIT) in your [License.md](https://github.com/aachal28/Awesome-web-development-resources/blob/main/License.md) first in your codebase so that others know that it is free to use, change, or even distribute.

Let me know once the changes are complete.

For more information: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Review by melvincwng — CHANGES_REQUESTED** [review]
Kindly address the 3 questions as mentioned above, and ping your reply to me over here. 

Thanks :smile:

**Comment by melvincwng** [comment]
@aachal28, I have reviewed the PR and overall PR looks good 👍🏻 

Once those 3 questions above are addressed, the PR would be good to go ⬆️

**Comment by melvincwng** [comment]
Resolve #126

**Comment by aachal28** [comment]
Thanks for review. 
1. I 'have joined the organization.
2. Yeah I'm going to update this resources repository currently it was not completed but I'm going to complete this week and try to update regularly.
3. updated MIT License to repository

**Comment by melvincwng** [comment]
> Thanks for review.
> 
> 1. I 'have joined the organization.
> 2. Yeah I'm going to update this resources repository currently it was not completed but I'm going to complete this week and try to update regularly.
> 3. updated MIT License to repository

Hi @aachal28, thanks for the swift response!

To add on for point 2, I also noticed some of your Web Development Resources links **might** be outdated (i.e. broken links). For example, in the screenshot below under the JavaScript section, the 'developer-cheatsheet' is outdated.

image

Hope you can look through your links again & I look forward to regular updates on your Web Developement Resource repository. You can take your time to continue working on this (no worries).

In view of all that, PR looks good and ready to be merged! 👍🏻 

**Just remember to regularly update your Web Development Resources repository with proper links & new additions** @aachal28

**Review by melvincwng — APPROVED** [review]
LGTM!

**Comment by melvincwng** [comment]
Thank you for your contribution to the community website @aachal28 

Happy Hacktoberfest 2023 🎉

**Comment by aachal28** [comment]
> > Thanks for review.
> > 
> > 1. I 'have joined the organization.
> > 2. Yeah I'm going to update this resources repository currently it was not completed but I'm going to complete this week and try to update regularly.
> > 3. updated MIT License to repository
> 
> Hi @aachal28, thanks for the swift response!
> 
> To add on for point 2, I also noticed one or two of your Web Development Resources links **might** be outdated (i.e. broken links). For example, in the screenshot below under the JavaScript section, the 'developer-cheatsheet' is outdated.
> 
> image
> 
> Hope you can look through your links again & I look forward to regular updates on your Web Development Resource repository. You can take your time to continue working on this (no worries).
> 
> In view of all that, PR looks good and ready to be merged! 👍🏻
> 
> **Just remember to regularly update your Web Development Resources repository with proper links & new additions** @aachal28

i'll check it and update all

**Pull request merged**
